// Generate code by cmake, don't modify
#ifndef ZSUDOVERSION_H
#define ZSUDOVERSION_H

#define ZSUDO_VERSION L"${ZSUDO_VERSION_MAJOR}.${ZSUDO_VERSION_MINOR}.${ZSUDO_VERSION_PATCH}"
#define ZSUDO_HASH L"${GIT_SHA1}"
#define ZSUDO_REFS L"${GIT_REFSPEC}"

#define ZSUDO_APPNAME L"zsudo-${ZSUDO_VERSION_MAJOR}.${ZSUDO_VERSION_MINOR}"

#endif